# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install --upgrade pip
  steps:
    - install:
        # Install from requirements.txt
        # "doc" dependencies will be in there too (Sphinx, etc).
        commands:
          - pip install -r requirements.txt
    - build:
        commands:
          - sphinx-build -b html docs/source docs/build/html